name: "Discord Commits"
description: "Send commit summary to Discord using custom templates"
branding:
  icon: "bell"
  color: "purple"
inputs:
  webhook:
    description: "discord webhook url without /github"
    required: true
  message:
    description: "A general message that is displayed for all commits. Defaults to the repo name."
  embed:
    description: "JSON string that accepts double braces for templates. Defaults to template's embed template"
  include-extras:
    description: "Boolean - Include extra embeds provided from templates."
  template:
    description: "The name of of a premade template."
  last-commit-only:
    description: "Boolean - only show the last commit."

runs:
  using: "node16"
  main: "discord-commits/index.mjs"
